<h2><i class="fas fa-cogs"></i>Administration</h2>

<h5><a href="editer.php">Rédiger un nouvel article</a></h5>
<h6>Liste des articles</h6>
<table>
	<tr>
		<td>Titre</td>
		<td>Article</td>
		<td>Auteur</td>
		<td>Categorie</td>
	
	<?php foreach ($articles as $article): ?>
		</tr>
			<td><?=$article['title']?></td>
			<?php
					$article['contentCut'] = substr($article['content'], 0, 10);
				?>
			<td><?=$article['contentCut']?></td>
			<td><?=$article['lastname']?><?=$article['firstname']?></td>
			<td><?=$article['name']?></td>
			<td><a href="modifier.php?id=<?=$article['id']?>">Modifier</a></td>
			<td><a href="delete.php">Effacer</a></td>
		</tr>
	<?php endforeach ?>

</table>