


<h2><i class="far fa-file-alt"></i>Article</h2>


<?php
$article['title'] = cleanText($article['title']);
$article['name'] = cleanText($article['name']);
$article['content'] = cleanText($article['content']);
$article['lastname'] = cleanText($article['lastname']);
$article['firstname'] = cleanText($article['firstname']);
$article['created_at'] = cleanText($article['created_at']);
?>

		<article>
			<h3><i class="far fa-hand-point-right"></i><?=$article['title']?></h3>
			<h6><?=$article['name']?></h6>
			<p><?= $article['content']?></p>
			<p class="author">Rédigé par <?=$article['lastname']?> <?=$article['firstname']?> le <?=$article['created_at']?></p>
		</article>
		
		<article class="commentaires">
	<?php foreach($comments as $comment): ?>
			<h6>Posté par : <?=$comment['pseudo']?></h6>
			<p><?=$comment['content']?></p>
			<p><?=$comment['created_at']?></p>
	<?php endforeach ?>
		</article>

<div class="commentaire">
	<fieldset>
		<legend>Nouveau commentaire</legend>
		<form action="comment.php" method="POST">
			<input type="text" name="idArticle" value="<?=$article['id']?>">
		 	<label for="pseudo">Pseudo</label>
		 	<textarea name="pseudo" id="pseudo" cols="60" rows="2"></textarea>
			<label for="comment">Commentaire</label>
			<textarea id="comment" name="comment" cols="60" rows="10" wrap="hard"></textarea>

			<button type="submit">Ajouter</button>
			<button type="reset">Annuler</button>

		</form>
	</fieldset>
</div>