<!DOCTYPE html>
<html lang="fr">
<head>
	<title>Blog</title>
	<meta charset="utf-8">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="main.css">
</head>
<body>
	<header class=container>
		<h1><a href="#">Encore un Blog ?! #nonMaisAllo</a></h1>
		<h4><a href="#"><i class="fas fa-cogs"></i>Administration</a>
	</header>
	<main class=container>